id: P47223F7F
initial_creation_type: input
source_metadata:
  Title: Sphuṭārthā Abhidharmakośa Vyākhyā (Vol 1)
  Editor: Narendra Nath Law
  Publisher: Luzac & Co.
  Place of Publication: London, England
  Year: '1949'
  Sphuṭārthā Abhidharmakośa Vyākhyā (Vol 2):
    Text Version: Romanized
    Input Personnel: Miroj Shakya
    Input Date: '2019'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:23:16.973296'
last_modified_at: '2022-03-08T17:23:16.973304'
